#!/bin/bash/

person1=KK
person2=Rajesh
person3=prabhu
person4=shiva
person5=bhargavi

echo "$person1: Hi $person2 how are you"
echo "$person2: Hi $person1 i'm good, where is $person3"
echo "$person1: I don't know about $person3"
echo "$person3: i'm here"
echo "$person4: hey there"
echo "$person5: hey there"
echo "$person2: hey there"